name: loni-ai2kit-tesla
scheduler: slurm

ai2kit:
  commands:
    controller_python: /project/lgutsev/env/iface_ai2kit_controller/bin/python
    ai2kit: /project/lgutsev/env/iface_ai2kit_controller/bin/ai2-kit
    omb: /project/lgutsev/env/iface_ai2kit_controller/bin/omb
    python: /project/lgutsev/env/iface_mace_runtime/bin/python
    mace: /project/lgutsev/env/iface_mace_runtime/bin/mace_run_train
  jobs: {train: mace_gpu, explore: openmm_gpu, label: vasp_cpu}
  potcar_source:
    Ti: /home/lgutsev/pot/potpaw_PBE/Ti_pv/POTCAR
    Si: /home/lgutsev/pot/potpaw_PBE/Si/POTCAR
    N: /home/lgutsev/pot/potpaw_PBE/N/POTCAR

jobs:
  mace_gpu:
    partition: gpu2
    account: loni_perovsk27
    nodes: 1
    ntasks: 1
    cpus_per_task: 8
    gpus: 1
    time: "48:00:00"
    modules: []
    environment: &gpu_environment
      OMP_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      CUDA_DEVICE_ORDER: PCI_BUS_ID
      PYTHONUNBUFFERED: "1"

  openmm_gpu:
    partition: gpu2
    account: loni_perovsk27
    nodes: 1
    ntasks: 1
    cpus_per_task: 8
    gpus: 1
    time: "12:00:00"
    modules: []
    environment: *gpu_environment

  vasp_cpu:
    partition: workq
    account: loni_perovsk27
    nodes: 1
    ntasks: 64
    cpus_per_task: 1
    time: "24:00:00"
    modules: [vasp6/6.5.1-cpu]
    environment: {OMP_NUM_THREADS: "1"}
    command: srun -n {ntasks} vasp_gam
